<?php

/**
 * PluginCidadeBrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCidadeBrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCidadeBrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCidadeBr');
    }
}